version: "3"

services:

  antechlicense:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
            MSSQL_PID: Express
            SA_PASSWORD: "bzKh8516"
            ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"